.github/workflows/build.yaml

As this could be a potential spam point for our GitHub because people might submit code without verifying if it compiles.
However, having this inside the CI allows us to cover a basic compilation test, which for some contributions may not require a full build. Additionally, we can ensure that the code compiles on basic Linux OS environments, like Ubuntu, or detect if there are any dependency breaks (even with minimal dependencies, so this shouldn't be an issue either).

ci: build datum inside the CI

---

src/datum_sockets.c
src/datum_stratum.c

There are a few places where DLOG gets too few args.
Can you verify if I did it right, please?

Too few arguments to formatting function DLOG

---

src/datum_logger.c
src/datum_stratum.c

It helped me find an issue in my config. The error message from fopen, and the filename I was trying to open

Improve error messages of fopen() calls

---

src/datum_logger.c

It's thread-safe and it's 4x faster too

Use localtime_r in get_midnight_timestamp()

---

src/datum_protocol.c

What happens is that you can get this in the log.
```
2024-12-10 17:30:02.356 [                       datum_protocol_client] ERROR: getaddrinfo: Name or service not known
2024-12-10 17:30:28.964 [               datum_gateway_template_thread] DEBUG: DEBUG: calling datum_gbt_parser (new=0)
```

Fix superfluous newline in log when getaddrinfo fails

---

src/datum_api.c
www/assets/style.css
www/clients_top.html
www/coinbaser_top.html
www/foot.html
www/home.html
www/threads_top.html

Minor cleanup of HTML/CSS for status pages:
- remove deprecated attribute on style element
- replace obsolete CENTER attribute using CSS classes
All HTML+CSS now validates cleanly. May be minor changes to spacing.

Bring status output to current web standards

---

src/datum_conf.c

This attempts to address @wizkid057's issue #38

Add a datum_conf.c check for no pool, but mining only

---

src/datum_blocktemplates.c
src/datum_stratum.c

Bugfix: stratum_calculate_merkle_branches would choke at > 8192 transactions in a template. Moved the temp data to a static variable, and bumped the size to appropriately match the max template size possible.
Added some additional sanity checks.

Bugfix: Max possible template transactions inconsistent across functions

---

src/datum_gateway.c

Socket state can change and be improperly handled in the brief time between epoll and any send(...) from the application's client send buffer. Since this can lead to a SIGPIPE, despite the sockets being non-blocking, the gateway will exit without any descriptive error if this happens.
EPIPE is handled properly by existing datum_socket code.

Bugfix: Socket state can change between epoll and send

---

src/datum_blocktemplates.c
src/datum_conf.c
src/datum_conf.h
src/datum_logger.c
src/datum_stratum.c
src/datum_submitblock.c

A handful of code quality improvements in how we sprintf to buffers:
1. Use sizeof() in snprintf to reduce the amount of hardcoded magic values that might be needed to update in the future consistently and therefore potentially lead to bugs. Also using sizeof() can catch certain classes of issues at compile time, eg.  ```warning: ‘snprintf’ output may be truncated before the last format character [-Wformat-truncation=]``` or ```note: ‘snprintf’ output between 2 and 512 bytes into a destination of size 511```
2. use 1024 bytes for userpass buffer consistently, this was found by using sizeof() above, actually
3. C99 snprintf() is OK to be called without subtracting 1 byte, we can stop bother to null terminate
4. prefer safer snprintf() instead sprintf() in places I found it makes sense

Improve use of sprintf and snprintf

---

src/datum_api.c
src/datum_conf.c
src/datum_conf.h
src/datum_utils.c
src/datum_utils.h

Requires an admin password to perform actions in the API
Password can be passed either with the POST (or GET for testnet fastforward) request, or using HTTP authentication (browser only).

API authentication

---

src/datum_api.c
src/datum_utils.c
src/datum_utils.h
www/home.html

To address #70
To existing current_time_millis() and current_time_micros() I've added current_time_seconds()
It uses clock_gettime() to ensure local time changes (NTP, timezones) don't affect the uptime.
Perhaps will become useful in other places?

Add datum process uptime

---

CMakeLists.txt
src/datum_api.c
src/datum_api.h
src/datum_blocktemplates.c
src/datum_conf.c
src/datum_conf.h
src/datum_gateway.c
src/datum_gateway.h
src/datum_jsonrpc.c
src/datum_jsonrpc.h
src/datum_utils.c
src/datum_utils.h
www/clients_top.html
www/coinbaser_top.html
www/config.html
www/config_errors.html
www/config_restart.html
www/home.html
www/threads_top.html

Built on top of #25
Mostly functional, two FIXMEs remain that should have minimal issues until followup. Would be nice to avoid restarting ever, but that can be a future improvement.

Support for editing config file (to an extent) via web dashboard

---

CMakeLists.txt
debian/rules

When merged into master, also fixes the "debian" doc dir used for the example JSON config.

Install README (and its diagram) to doc dir (incl. bugfix)

---

src/datum_api.c

Safari only supports MD5 hashing for Digest HTTP authentication

api: Workaround Safari negligence by falling back to MD5 digest for it alone

---

src/datum_sockets.c

Bugfix: sockets: Ensure listen_socks[1] is always initialized

---

src/datum_conf.c

The real limit is less 1 to leave room for a trailing null byte.

Bugfix: Report correct maximum lengths in user error

---

.github/workflows/build.yaml
CMakeLists.txt
src/datum_conf.c
src/datum_gateway.c

CI: Use Docker to test Debian, AmazonLinux, Fedora, Alma, Oracle, Arch, and Clear Linux, with both GCC and Clang

---

.github/workflows/build.yaml
CMakeLists.txt
src/datum_conf.c
src/datum_gateway.c

build: Fall back to C11 for CMake <3.21

---

.github/workflows/build.yaml

Because Gentoo compiles LLVM etc, this uses GitHub Actions caches to save the binaries across compatible runs

CI: Build for Alpine and Gentoo (incl Gentoo musl)
